name: "Antigravity Remote Control"
slug: "antigravity_remote_control"
description: "Headless Google Antigravity Remote Control daemon & local AI microservice for Home Assistant"
version: "1.2.11"
arch:
  - amd64
  - aarch64
startup: "services"
boot: "auto"
init: false
hassio_api: true
hassio_role: "manager"
homeassistant_api: true
host_network: true
map:
  - homeassistant_config:rw
  - share:rw
  - ssl:ro
options:
  instance_name: "homeassistant"
schema:
  instance_name: "str"
